name = glass_sounds
min_minetest_version = 5.0.0
author = ZenonSeth
description = Replaces the glass sounds for default/mcl_sounds with more natural variations
title = Glass Sounds
optional_depends = default, mcl_sounds
